name: Deploy Lambda Function

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install awscli
          pip install -r requirements.txt --target ./packages

      - name: Zip the function and dependencies
        run: |
          cd packages
          zip -r ../function.zip .
          cd ..
          zip -g function.zip lambda_function.py

      - name: Deploy to AWS Lambda
        env:
          AWS_REGION: eu-south-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          LAMBDA_FUNCTION_NAME: relay-webhook-zapier
          RELEVANTAI_PROJECT_ID: ${{ secrets.RELEVANTAI_PROJECT_ID }}
          RELEVANTAI_API_URL: ${{ secrets.RELEVANTAI_API_URL }}
        run: |
          # Update env vars
          aws lambda update-function-configuration --function-name $LAMBDA_FUNCTION_NAME --environment Variables="{RELEVANTAI_PROJECT_ID=$RELEVANTAI_PROJECT_ID,RELEVANTAI_API_URL=$RELEVANTAI_API_URL}" --region $AWS_REGION
          # Update the function code
          aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --zip-file fileb://function.zip --publish --region $AWS_REGION
