name: Deploy Lambda Function

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install awscli

      - name: Zip the function
        run: |
          zip -r function.zip lambda_function.py

      - name: Deploy to AWS Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-south-1
          LAMBDA_FUNCTION_NAME: relay-webhook-zapier
          RELEVANTAI_PROJECT_ID: ${{ secrets.RELEVANTAI_PROJECT_ID }}
          RELEVANTAI_API_URL: ${{ secrets.RELEVANTAI_API_URL }}
        run: |
          # Update the function code
          aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --zip-file fileb://function.zip --publish --region $AWS_REGION

          # Wait loop for update-function-configuration to be ready (max 10 retries with 10 seconds delay)
          MAX_RETRIES=10
          DELAY_SECONDS=10
          for ((i=1;i<=MAX_RETRIES;i++)); do
            echo "Attempt $i to update function configuration..."
            if aws lambda update-function-configuration --function-name $LAMBDA_FUNCTION_NAME --environment Variables="{RELEVANTAI_PROJECT_ID=$RELEVANTAI_PROJECT_ID,RELEVANTAI_API_URL=$RELEVANTAI_API_URL}" --region $AWS_REGION; then
              echo "Update function configuration succeeded"
              break
            else
              echo "Update function configuration failed, retrying in $DELAY_SECONDS seconds..."
              sleep $DELAY_SECONDS
            fi
          done
          if [ $i -gt $MAX_RETRIES ]; then
            echo "Failed to update function configuration after $MAX_RETRIES attempts"
            exit 1
          fi
